# Site settings
title: Senior Systems administrator
email: redacted@unavailable.tld.none
description: > # this means to ignore newlines until "baseurl:"
  This is a standard sysadmin blog, where I write stuff worth sharing from my work, and tech. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://opentokix.github.io" # the base hostname & protocol for your site
twitter_username: opentokix
github_username:  opentokix

# Build settings
markdown: kramdown
timezone: Europe/Stockholm
